--------------------------------------------------------
--  Fichier créé - mardi-janvier-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONGE1
--------------------------------------------------------

  CREATE TABLE "MEHDI"."CONGE1" 
   (	"CODECONGE" NUMBER, 
	"IDEMPLOYE" NUMBER, 
	"SOLDE" NUMBER, 
	"HISTORIQUECONGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CRUD
--------------------------------------------------------

  CREATE TABLE "MEHDI"."CRUD" 
   (	"NUM_COLIS" NUMBER(*,0), 
	"DEPART" VARCHAR2(20 BYTE), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"DATE_ENVOI" VARCHAR2(20 BYTE), 
	"ASSURANCE" VARCHAR2(20 BYTE), 
	"POIDS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CRUD1
--------------------------------------------------------

  CREATE TABLE "MEHDI"."CRUD1" 
   (	"CODE_LIVRAISON" NUMBER, 
	"LIVREUR" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"DISTANCE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEVIS
--------------------------------------------------------

  CREATE TABLE "MEHDI"."DEVIS" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"TYPE_DE_LIVRAISON" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"ID_FOURNISSEUR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "MEHDI"."EMPLOYE" 
   (	"IDEMP" NUMBER, 
	"NOMEMP" VARCHAR2(20 BYTE), 
	"DATEDENAISSANCEEMP" DATE, 
	"EMAILEMP" VARCHAR2(20 BYTE), 
	"POSTEEMP" VARCHAR2(20 BYTE), 
	"CODECARTE" VARCHAR2(20 BYTE), 
	"HISTORIQUEACCES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENREGISTREMENT
--------------------------------------------------------

  CREATE TABLE "MEHDI"."ENREGISTREMENT" 
   (	"NUMERO_DE_LIVRAISON" NUMBER, 
	"TYPE_DE_RECLAMATION" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"DATE_DE_RECLAMATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "MEHDI"."FOURNISSEUR" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE
--------------------------------------------------------

  CREATE TABLE "MEHDI"."HISTORIQUE" 
   (	"IDENTIFIANT_RECLAMATION" VARCHAR2(20 BYTE), 
	"DATE_" VARCHAR2(20 BYTE), 
	"NOMBRE_DE_RECLAMATION" NUMBER, 
	"POURCENTAGE_DE_RECLAMATION" VARCHAR2(20 BYTE), 
	"POURCENTAGE_AUGMENTATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE_CLIENTS
--------------------------------------------------------

  CREATE TABLE "MEHDI"."HISTORIQUE_CLIENTS" 
   (	"ID_HISTORIQUE" VARCHAR2(20 BYTE), 
	"NOM_HISTORIQUE" VARCHAR2(20 BYTE), 
	"PRENOM_HISTORIQUE" VARCHAR2(20 BYTE), 
	"CIN_HISTORIQUE" VARCHAR2(20 BYTE), 
	"NUM_TELEPHONE_HISTORIQUE" VARCHAR2(20 BYTE), 
	"DATE_COMMANDE_HISTORIQUE" DATE, 
	"PROMOTION_HISTORIQUE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTIONS
--------------------------------------------------------

  CREATE TABLE "MEHDI"."PROMOTIONS" 
   (	"ID_PROMOTION" VARCHAR2(20 BYTE), 
	"PRIX_PROMOTION" FLOAT(126), 
	"NOM_PROMOTION" VARCHAR2(20 BYTE), 
	"DATEDEB_PROMOTION" DATE, 
	"DATEFIN_PROMOTION" DATE, 
	"DESCRIPTION_PROMOTION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SIGNUP
--------------------------------------------------------

  CREATE TABLE "MEHDI"."SIGNUP" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MEHDI.CONGE1
SET DEFINE OFF;
REM INSERTING into MEHDI.CRUD
SET DEFINE OFF;
Insert into MEHDI.CRUD (NUM_COLIS,DEPART,DESTINATION,DATE_ENVOI,ASSURANCE,POIDS) values ('1221','cghch','chhc','03.12.2020','Sans assurance','1 KG -');
REM INSERTING into MEHDI.CRUD1
SET DEFINE OFF;
REM INSERTING into MEHDI.DEVIS
SET DEFINE OFF;
Insert into MEHDI.DEVIS (CODE,DESTINATION,TYPE_DE_LIVRAISON,QUANTITE,PRIX,ID_FOURNISSEUR) values ('123ER','gabes','payant','12packets','19,5 DT ','00234OP');
REM INSERTING into MEHDI.EMPLOYE
SET DEFINE OFF;
Insert into MEHDI.EMPLOYE (IDEMP,NOMEMP,DATEDENAISSANCEEMP,EMAILEMP,POSTEEMP,CODECARTE,HISTORIQUEACCES) values ('12','12',to_date('01/01/00','DD/MM/RR'),'12','12','12','12');
REM INSERTING into MEHDI.ENREGISTREMENT
SET DEFINE OFF;
REM INSERTING into MEHDI.FOURNISSEUR
SET DEFINE OFF;
Insert into MEHDI.FOURNISSEUR (ID,NOM,PRENOM,ADRESSE,CIN) values ('aa','zzer','tr','j',null);
REM INSERTING into MEHDI.HISTORIQUE
SET DEFINE OFF;
REM INSERTING into MEHDI.HISTORIQUE_CLIENTS
SET DEFINE OFF;
Insert into MEHDI.HISTORIQUE_CLIENTS (ID_HISTORIQUE,NOM_HISTORIQUE,PRENOM_HISTORIQUE,CIN_HISTORIQUE,NUM_TELEPHONE_HISTORIQUE,DATE_COMMANDE_HISTORIQUE,PROMOTION_HISTORIQUE) values ('H003','Ayari','mohamed emin','13452678','23550904',to_date('10/10/20','DD/MM/RR'),'oui');
Insert into MEHDI.HISTORIQUE_CLIENTS (ID_HISTORIQUE,NOM_HISTORIQUE,PRENOM_HISTORIQUE,CIN_HISTORIQUE,NUM_TELEPHONE_HISTORIQUE,DATE_COMMANDE_HISTORIQUE,PROMOTION_HISTORIQUE) values ('H001','mehdi','benattia','14444444','55667788',to_date('10/10/09','DD/MM/RR'),'oui');
Insert into MEHDI.HISTORIQUE_CLIENTS (ID_HISTORIQUE,NOM_HISTORIQUE,PRENOM_HISTORIQUE,CIN_HISTORIQUE,NUM_TELEPHONE_HISTORIQUE,DATE_COMMANDE_HISTORIQUE,PROMOTION_HISTORIQUE) values ('H002','mejri','mohamed aziz','16879898','56897845',to_date('10/10/20','DD/MM/RR'),'non');
Insert into MEHDI.HISTORIQUE_CLIENTS (ID_HISTORIQUE,NOM_HISTORIQUE,PRENOM_HISTORIQUE,CIN_HISTORIQUE,NUM_TELEPHONE_HISTORIQUE,DATE_COMMANDE_HISTORIQUE,PROMOTION_HISTORIQUE) values ('H004','mehdi','montadhar','16548798','50104251',to_date('29/10/19','DD/MM/RR'),'non');
Insert into MEHDI.HISTORIQUE_CLIENTS (ID_HISTORIQUE,NOM_HISTORIQUE,PRENOM_HISTORIQUE,CIN_HISTORIQUE,NUM_TELEPHONE_HISTORIQUE,DATE_COMMANDE_HISTORIQUE,PROMOTION_HISTORIQUE) values ('H005','ben adda','karim','14986534','51963369',to_date('20/11/20','DD/MM/RR'),'oui');
Insert into MEHDI.HISTORIQUE_CLIENTS (ID_HISTORIQUE,NOM_HISTORIQUE,PRENOM_HISTORIQUE,CIN_HISTORIQUE,NUM_TELEPHONE_HISTORIQUE,DATE_COMMANDE_HISTORIQUE,PROMOTION_HISTORIQUE) values ('H006','jbeli','hamadi','16879865','20548798',to_date('29/12/07','DD/MM/RR'),'non');
REM INSERTING into MEHDI.PROMOTIONS
SET DEFINE OFF;
Insert into MEHDI.PROMOTIONS (ID_PROMOTION,PRIX_PROMOTION,NOM_PROMOTION,DATEDEB_PROMOTION,DATEFIN_PROMOTION,DESCRIPTION_PROMOTION) values ('P001','10000','Offre aajab',to_date('10/10/01','DD/MM/RR'),to_date('10/12/01','DD/MM/RR'),'offre puissant ');
Insert into MEHDI.PROMOTIONS (ID_PROMOTION,PRIX_PROMOTION,NOM_PROMOTION,DATEDEB_PROMOTION,DATEFIN_PROMOTION,DESCRIPTION_PROMOTION) values ('P002','20000','orange',to_date('12/12/09','DD/MM/RR'),to_date('12/12/10','DD/MM/RR'),'orange');
Insert into MEHDI.PROMOTIONS (ID_PROMOTION,PRIX_PROMOTION,NOM_PROMOTION,DATEDEB_PROMOTION,DATEFIN_PROMOTION,DESCRIPTION_PROMOTION) values ('P003','15000','telecom',to_date('09/09/14','DD/MM/RR'),to_date('09/09/15','DD/MM/RR'),'sfqqdcq');
Insert into MEHDI.PROMOTIONS (ID_PROMOTION,PRIX_PROMOTION,NOM_PROMOTION,DATEDEB_PROMOTION,DATEFIN_PROMOTION,DESCRIPTION_PROMOTION) values ('P004','3000','taraji',to_date('19/10/19','DD/MM/RR'),to_date('20/02/20','DD/MM/RR'),'taraji mobile');
Insert into MEHDI.PROMOTIONS (ID_PROMOTION,PRIX_PROMOTION,NOM_PROMOTION,DATEDEB_PROMOTION,DATEFIN_PROMOTION,DESCRIPTION_PROMOTION) values ('P006','5000','souissi',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'hfgkuhb');
REM INSERTING into MEHDI.SIGNUP
SET DEFINE OFF;
Insert into MEHDI.SIGNUP (USERNAME,PASSWORD,NAME,POSTE) values ('mba','123456','mehdi ben attia','R.Marketing');
Insert into MEHDI.SIGNUP (USERNAME,PASSWORD,NAME,POSTE) values (null,null,null,'R.H');
Insert into MEHDI.SIGNUP (USERNAME,PASSWORD,NAME,POSTE) values (null,null,null,'R.H');
Insert into MEHDI.SIGNUP (USERNAME,PASSWORD,NAME,POSTE) values ('rgaya','123456','mohamed emin rgaya','R.Parking');
--------------------------------------------------------
--  DDL for Index HISTORIQUE_CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."HISTORIQUE_CLIENTS_PK" ON "MEHDI"."HISTORIQUE_CLIENTS" ("ID_HISTORIQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONGE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."CONGE1_PK" ON "MEHDI"."CONGE1" ("CODECONGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."PROMOTIONS_PK" ON "MEHDI"."PROMOTIONS" ("ID_PROMOTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HISTORIQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."HISTORIQUE_PK" ON "MEHDI"."HISTORIQUE" ("NOMBRE_DE_RECLAMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEVIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."DEVIS_PK" ON "MEHDI"."DEVIS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."TABLE1_PK" ON "MEHDI"."FOURNISSEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENREGISTREMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEHDI"."ENREGISTREMENT_PK" ON "MEHDI"."ENREGISTREMENT" ("NUMERO_DE_LIVRAISON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ENREGISTREMENT
--------------------------------------------------------

  ALTER TABLE "MEHDI"."ENREGISTREMENT" ADD CONSTRAINT "ENREGISTREMENT_PK" PRIMARY KEY ("NUMERO_DE_LIVRAISON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."ENREGISTREMENT" MODIFY ("NUMERO_DE_LIVRAISON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."EMPLOYE" MODIFY ("IDEMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTIONS
--------------------------------------------------------

  ALTER TABLE "MEHDI"."PROMOTIONS" ADD CONSTRAINT "PROMOTIONS_PK" PRIMARY KEY ("ID_PROMOTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."PROMOTIONS" MODIFY ("ID_PROMOTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "MEHDI"."FOURNISSEUR" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIQUE
--------------------------------------------------------

  ALTER TABLE "MEHDI"."HISTORIQUE" ADD CONSTRAINT "HISTORIQUE_PK" PRIMARY KEY ("NOMBRE_DE_RECLAMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."HISTORIQUE" MODIFY ("NOMBRE_DE_RECLAMATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVIS
--------------------------------------------------------

  ALTER TABLE "MEHDI"."DEVIS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."DEVIS" ADD CONSTRAINT "DEVIS_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONGE1
--------------------------------------------------------

  ALTER TABLE "MEHDI"."CONGE1" MODIFY ("CODECONGE" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."CONGE1" ADD CONSTRAINT "CONGE1_PK" PRIMARY KEY ("CODECONGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIQUE_CLIENTS
--------------------------------------------------------

  ALTER TABLE "MEHDI"."HISTORIQUE_CLIENTS" ADD CONSTRAINT "HISTORIQUE_CLIENTS_PK" PRIMARY KEY ("ID_HISTORIQUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEHDI"."HISTORIQUE_CLIENTS" MODIFY ("CIN_HISTORIQUE" NOT NULL ENABLE);
  ALTER TABLE "MEHDI"."HISTORIQUE_CLIENTS" MODIFY ("ID_HISTORIQUE" NOT NULL ENABLE);
